//an array of countries and their country codes
export const CountryList = [
  {label: 'Argentina', value: 'ar'},
  {label: 'Australia', value: 'au'},
  {label: 'Austria', value: 'at'},
  {label: 'Belgium', value: 'be'},
  {label: 'Brazil', value: 'br'},
  {label: 'Bulgaria', value: 'bg'},
  {label: 'California', value: 'ca'},
  {label: 'Colombia', value: 'co'},
  {label: 'Cuba', value: 'cu'},
  {label: 'Czech R.', value: 'cz'},
  {label: 'Egypt', value: 'eg'},
  {label: 'France', value: 'fr'},
  {label: 'Germany', value: 'de'},
  {label: 'Ghana', value: 'gh'},
  {label: 'Greece', value: 'gr'},
  {label: 'Hong Kong', value: 'hk'},
  {label: 'Hungary', value: 'hu'},
  {label: 'Indonesia', value: 'id'},
  {label: 'Ireland', value: 'ie'},
  {label: 'Israel', value: 'il'},
  {label: 'Italy', value: 'it'},
  {label: 'Japan', value: 'jp'},
  {label: 'Latvia', value: 'lv'},
  {label: 'Lithuania', value: 'lt'},
  {label: 'Malaysia', value: 'my'},
  {label: 'Mexico', value: 'mx'},
  {label: 'Morocco', value: 'ma'},
  {label: 'Netherlands', value: 'nl'},
  {label: 'New Zealand', value: 'nz'},
  {label: 'Nigeria', value: 'ng'},
  {label: 'Philippines', value: 'ph'},
  {label: 'Poland', value: 'pl'},
  {label: 'Portugal', value: 'pt'},
  {label: 'PRC', value: 'cn'},
  {label: 'Romania', value: 'ro'},
  {label: 'Russian Federation', value: 'ru'},
  {label: 'R. Serbia', value: 'rs'},
  {label: 'R. South Africa', value: 'sa'},
  {label: 'Singapore', value: 'sg'},
  {label: 'Slovakia', value: 'sk'},
  {label: 'Slovenia', value: 'si'},
  {label: 'South Africa', value: 'za'},
  {label: 'South Korea', value: 'kr'},
  {label: 'Sweden', value: 'se'},
  {label: 'Switzerland', value: 'ch'},
  {label: 'Taiwan', value: 'tw'},
  {label: 'Thailand', value: 'th'},
  {label: 'Turkey', value: 'tr'},
  {label: 'UAE', value: 'ae'},
  {label: 'UK', value: 'gb'},
  {label: 'Ukraine', value: 'ua'},
  {label: 'USA', value: 'us'},
  {label: 'Venezuela', value: 've'},
];
